### ISSUE TITLE
Availability of protoc-gen-validate plugins

### ISSUE THREAD

**Issue by trietsch** [bufbuild/plugins#202] opened 2022-11-07 10:48 UTC
Hi! I just noticed that the `protoc-gen-validate` plugins for `cpp`, `java,` and `go` are present in this repository, but they are not available in the [BSR](https://buf.build/bufbuild/plugins). Is that intentional?

Thanks!

**Comment by mfridman** [comment] 2022-11-07 14:58
Hi @trietsch, you've bumped into an upcoming feature. We'll have more updates in the coming weeks, stay tuned.

Going to close this for now, as this is intended behaviour.

**Closed by mfridman** 2022-11-07 14:58 UTC

**Comment by varnastadeus** [comment] 2022-12-05 11:01
any news on this? 🙏

**Comment by mfridman** [comment] 2022-12-05 15:30
Hey @varnastadeus, all Buf-managed plugins can be viewed on https://buf.build/plugins. There is also a dedicated plugin page with more information here:

https://buf.build/bufbuild/validate-go
https://buf.build/bufbuild/validate-java
https://buf.build/bufbuild/validate-cpp

It can be used with newer `buf` CLI versions (>v1.9.0) with the new `plugin` key (instead of `remote` or `name`):

```
# buf.gen.yaml

version: v1
plugins:
  - plugin: buf.build/bufbuild/validate-go
    out: gen
```

Note, this plugin used to require a `lang` option, but we instead broken up the plugin so you reference the one you need by name and we automatically add the option.

### Available on https://buf.build/plugins

<img width="903" alt="CleanShot 2022-12-05 at 10 25 18@2x" src="https://user-images.githubusercontent.com/6278244/205675416-2eb1c7f7-0672-42cf-aa73-47506048c321.png">
